### ISSUE TITLE
MinimizeToTray is not work

### ISSUE THREAD

**Issue by sarla999** [nmaier/mintrayr#142]
my MinimizeToTray version is 1.1.2.1-signed  and it not work on thunderbird 38.2.0  , when I click the button , I got the error  "Timestamp: 2015年08月28日 17时36分11秒
Error: TypeError: gMinTrayR.minimize is not a function
Source File: chrome://messenger/content/messenger.xul
Line: 1"   from errorconsole . 

my OS is ubuntu 14.04 .

**Comment by thomai** [comment]
Same here in Mint 17.2

Error log:
```
Timestamp: 09/06/2015 04:41:38 PM
Error: TypeError: gMinTrayR.minimize is not a function
Source File: chrome://messenger/content/messenger.xul
Line: 1
```

**Comment by Dobatymo** [comment]
Same here for v38.2.0 on Win7 Pro x64

    Error: TypeError: gMinTrayR.minimize is not a function
    Source File: chrome://messenger/content/messenger.xul
    Line: 1

**Comment by thomai** [comment]
Could you please update the add-on in the [Thunderbird portal](https://addons.mozilla.org/En-uS/thunderbird/addon/minimizetotray-revived/) too?
